name 'purplehazech-syslog-ng'
version '0.0.1'

author 'Lucas S. Bickel'
license 'see README.rdoc'
project_page 'https://github.com/purplehazech/puppet-syslog-ng'
source 'https://github.com/purplehazech/puppet-zabbix.git'
summary 'install and configure syslog-ng'
description 'Install and configure syslog-ng'
dependency 'puppetlabs/stdlib', '~3.2.0'
