name 'purplehazech-syslogng'
version '0.1.0'

author 'Lucas S. Bickel'
license 'AGPL3+'
project_page 'https://github.com/purplehazech/puppet-syslogng'
source 'https://github.com/purplehazech/puppet-zabbix.git'
summary 'install and configure syslog-ng'
description 'Install and configure syslog-ng'
dependency 'puppetlabs/stdlib', '~3.2.0'
